team_name_to_abbreviation = {
    "Team Vitality": "VIT",
    "Team Liquid": "TL",
    "Team Heretics": "TH",
    "FUT Esports": "FUT",
    "FNATIC": "FNC",
    "BBL Esports": "BBL",
    "Gentle Mates": "M8",
    "GIANTX": "GX",
    "KOI": "KOI",
    "Natus Vincere": "NAVI",
    "Karmine Corp": "KC",
    "Apeks": "APK",
    "DRX": "DRX",
    "T1": "T1",
    "Gen.G": "GEN",
    "TALON": "TLN",
    "Nongshim RedForce": "NS",
    "DetonatioN FocusMe": "DFM",
    "Rex Regum Qeon": "RRQ",
    "Paper Rex": "PRX",
    "BOOM Esports": "BME",
    "Team Secret": "TS",
    "Global Esports": "GE",
    "ZETA DIVISION": "ZETA",
    "G2 Esports": "G2",
    "Sentinels": "SEN",
    "MIBR": "MIBR",
    "KRÜ Esports": "KRÜ",
    "LEVIATÁN": "LEV",
    "LOUD": "LOUD",
    "Evil Geniuses": "EG",
    "NRG Esports": "NRG",
    "FURIA": "FUR",
    "Cloud9": "C9",
    "100 Thieves": "100T",
    "2Game Esports": "2G",
    "EDward Gaming": "EDG",
    "Trace Esports": "TE",
    "Bilibili Gaming": "BLG",
    "Dragon Ranger Gaming": "DRG",
    "FunPlus Phoenix": "FPX",
    "Xi Lai Gaming": "XLG",
    "Nova Esports": "NOVA",
    "JDG Esports": "JDG",
    "Wolves Esports": "WOL",
    "TYLOO": "TYL",
    "Titan Esports Club": "TEC",
    "All Gamers": "AG"
}

teams = {
        "Team Vitality", 
        "Team Liquid", 
        "Team Heretics", 
        "FUT Esports", 
        "FNATIC", 
        "BBL Esports", 
        "Gentle Mates", 
        "GIANTX",  
        "KOI", 
        "Natus Vincere", 
        "Karmine Corp", 
        "Apeks", 
        "DRX", 
        "T1",  
        "Gen.G", 
        "TALON", 
        "Nongshim RedForce", 
        "DetonatioN FocusMe", 
        "Rex Regum Qeon", 
        "Paper Rex", 
        "BOOM Esports", 
        "Team Secret", 
        "Global Esports", 
        "ZETA DIVISION", 
        "G2 Esports", 
        "Sentinels",  
        "MIBR", 
        "KRÜ Esports",  
        "LEVIAT\u00c1N", 
        "LOUD", 
        "Evil Geniuses", 
        "NRG Esports",  
        "FURIA", 
        "Cloud9", 
        "100 Thieves", 
        "2Game Esports", 
        "EDward Gaming", 
        "Trace Esports", 
        "Bilibili Gaming", 
        "Dragon Ranger Gaming", 
        "FunPlus Phoenix",  
        "Xi Lai Gaming", 
        "Nova Esports", 
        "JDG Esports", 
        "Wolves Esports", 
        "TYLOO", 
        "Titan Esports Club", 
        "All Gamers" 
        }

player_teams = {
        "VIT", 
        "TL",  
        "TH", 
        "FUT", 
        "FNC", 
        "BBL", 
        "M8", 
        "GX", 
        "KOI", 
        "NAVI", 
        "KC", 
        "APK", 
        "DRX", 
        "T1", 
        "GEN", 
        "TLN", 
        "NS", 
        "DFM", 
        "RRQ", 
        "PRX", 
        "BME", 
        "TS", 
        "GE", 
        "ZETA", 
        "G2", 
        "SEN", 
        "MIBR", 
        "KRÜ", 
        "LEV", 
        "LOUD", 
        "EG", 
        "NRG", 
        "FUR", 
        "C9", 
        "100T", 
        "2G", 
        "EDG", 
        "TE", 
        "BLG", 
        "DRG", 
        "FPX", 
        "XLG", 
        "NOVA", 
        "JDG", 
        "WOL", 
        "TYL", 
        "TEC", 
        "AG" 
}        